### ISSUE TITLE
Collection as Data (?)

### ISSUE THREAD

**Issue by owenmonroe** [digitalhogarth/digitalhogarth.github.io#15]
Do we want to keep a downloadable Collection as data section? Would we want to present a metadata csv or something different?

**Comment by danieljohnevans** [comment]
Great idea @owenmonroe , i think this functionality is actually included in Collection Builder:

-- Click to Data page 
-- Click either CSV or Excel buttons to download entirety of data

Feel free to close issue if this is what you are thinking
